### ISSUE TITLE
错误: 找不到或无法加载主类 JFlex.Main

### ISSUE THREAD

**Issue by pwelyn** [rover12421/ShakaApktool#14]
$ gradle fatjar
Incremental java compilation is an incubating feature.
:shaka.lib:compileAspect
Download https://repo1.maven.org/maven2/org/aspectj/aspectjtools/1.8.4/aspectjtools-1.8.4.pom
Download https://repo1.maven.org/maven2/org/aspectj/aspectjtools/1.8.4/aspectjtools-1.8.4.jar
:shaka.lib:compileJava
:shaka.lib:deleteProperties UP-TO-DATE
:shaka.lib:processResources
:shaka.lib:classes
:shaka.lib:jar
:shaka.smali:generateGrammarSource UP-TO-DATE
:shaka.smali:generateJFlexSource
错误: 找不到或无法加载主类 JFlex.Main
:shaka.smali:generateJFlexSource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shaka.smali:generateJFlexSource'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 4.494 secs

尝试多次不行，只有反馈过来不知道是不是个人问题

**Comment by rover12421** [comment]
fjlex plugin 升级到 0.0.2的问题.
会尽快修复

**Comment by rover12421** [comment]
fix:7032b39bf809bf07472457442c7c3fae0f6028c5

**Comment by pwelyn** [comment]
Download https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5/antlr-runtime-3.5.jar
:shaka.lib:compileAspect
Download https://repo1.maven.org/maven2/org/aspectj/aspectjtools/1.8.4/aspectjtools-1.8.4.pom
Download https://repo1.maven.org/maven2/org/aspectj/aspectjtools/1.8.4/aspectjtools-1.8.4.jar
:shaka.lib:compileJava
:shaka.lib:deleteProperties UP-TO-DATE
:shaka.lib:processResources
:shaka.lib:classes
:shaka.lib:jar
:shaka.smali:compileAspect
:shaka.smali:generateGrammarSource
:shaka.smali:generateJFlexSource
Download https://repo1.maven.org/maven2/de/jflex/jflex/1.6.1/jflex-1.6.1.pom
Download https://repo1.maven.org/maven2/de/jflex/jflex-parent/1.6.1/jflex-parent-1.6.1.pom
Download https://repo1.maven.org/maven2/de/jflex/jflex/1.6.1/jflex-1.6.1.jar
错误: 找不到或无法加载主类 JFlex.Main
:shaka.smali:generateJFlexSource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shaka.smali:generateJFlexSource'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 54.074 secs

还是存在额 麻烦看一下

**Comment by rover12421** [comment]
这个已经在 https://github.com/rover12421/ShakaApktool/commit/7032b39bf809bf07472457442c7c3fae0f6028c5 修复过了. 再`build`时候不会主动调用`generateJFlexSource`.语法分析代码已经加到git仓库里了

**Comment by rover12421** [comment]
jflex 插件引发的问题,考虑从gradle中掉语法生成器的配置

**Comment by pwelyn** [comment]
如果我在编译的时候直接跳过generateJFlexSource 应该不会有什么影响吧
