### ISSUE TITLE
/res/raw下xml文件的反编译问题

### ISSUE THREAD

**Issue by Ezalor** [rover12421/ShakaApktool#16]
/res/raw下有xml文件时，会提示无法反编译文件，用FALSE值代替，然后这个xml文件就成了0kb，在/res/values/raw.xml中会添加FALSE。但实际上/res/raw下的xml文件貌似不用反编译。

谢谢！

**Comment by rover12421** [comment]
/res/raw下的所有文件都应该不反编译的.
是否可以上传一个测试包

**Comment by Ezalor** [comment]
额，貌似我来晚了。。好像已经修复了？。。
http://coolapk.com/apk/com.afast.launcher
测试了一下这一个，没问题了~

另：为什么apktool的版本号更新到10天前了？。。

多谢~

**Comment by rover12421** [comment]
这个没注意,你可以先自行update下.可能是我在apktool目录下执行checkout master的时候回滚过去了...
