### ISSUE TITLE
jetBrains

### ISSUE THREAD

**Issue by rasulian** [rover12421/ShakaApktool#30]
Hi.
May i request for phpstorm 10 patch keygen ?

**Comment by rover12421** [comment]
Jetbrains IDE Crack V2 Download :
http://pan.baidu.com/s/1hq0fKck
https://drive.google.com/file/d/0Bys5uLXCK_sVVHRjQ3NwblRQams/view?usp=sharing
https://www.dropbox.com/s/ys2cls9wnybvai6/JetbrainsCrack.zip?dl=0

**Comment by rasulian** [comment]
Thanks a lot!
I did what you saw in ReadMe file but after running ./phpstorm.sh , I got these errors:
http://pastebin.com/d8QZehun 
what should i do?

**Comment by rover12421** [comment]
Jetbrains IDE Crack V2.1 Download :
http://pan.baidu.com/s/1hq0fKck
https://www.dropbox.com/s/qb9ihriyh11darz/JetbrainsCrackV2.1.zip?dl=0
https://drive.google.com/file/d/0Bys5uLXCK_sVcUw2YWJfcDQ1alU/view?usp=sharing

Jetbrains IDE Crack Source
http://pan.baidu.com/s/1hq0fKck
https://www.dropbox.com/s/01rn4h5j7na5ecc/JetbrainsCrack.src.zip?dl=0
https://drive.google.com/file/d/0Bys5uLXCK_sVRHQzSDhoRjFCbkE/view?usp=sharing

**Comment by rover12421** [comment]
Try again.

**Comment by rasulian** [comment]
Thank you again :+1: 
It worked Exactly like a Charm!

**Comment by roshan-** [comment]
@rover12421 
This crack doesn't work for 15.0.2, right?
