### ISSUE TITLE
dex offset 的问题。。

### ISSUE THREAD

**Issue by Ezalor** [rover12421/ShakaApktool#31]
http://coolapk.com/apk/eliseo.nightmode

在反编译这个的时候，会出现无数的offset的提示（刚更新的没有提示了，但下面的问题还有），
好多类似于
```
.method abstract a()V
.end method
```
的方法，都会变成
```
# write writeVirtualMethods error : a()V
```
然后回编译就不能用了，会直接FC。。

麻烦大神看一下，谢谢！~

**Comment by rover12421** [comment]
fix cf396b12c99205adfb8ea66a7d3b7968ef82ed78
