### ISSUE TITLE
最近的版本反编译好慢，请问能优化一下吗？

### ISSUE THREAD

**Issue by Ezalor** [rover12421/ShakaApktool#36]
最近的版本反编译需要好长时间，是新添加的功能的问题吗？大神能不能优化一下。。或者加个开关？

**Comment by rover12421** [comment]
25号的也很慢么?

**Comment by Ezalor** [comment]
嗯，特别慢。。。一个APK有时候要好几分钟才能完。
好像是慢在dex上

**Comment by rover12421** [comment]
你下个25号以后的版本试试

**Comment by Ezalor** [comment]
试了下，还是非常慢。。。

**Comment by rover12421** [comment]
和原版比较呢,有慢多少

**Comment by Ezalor** [comment]
慢4-5倍吧

**Comment by rover12421** [comment]
fix 1dd5a9d744e482a8e32fe19377aaacba2777dc28

➜  Desktop  time java -jar apktool_2.0.2.jar d -r weixin637android660.apk -f
I: Using Apktool 2.0.2 on weixin637android660.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
java -jar apktool_2.0.2.jar d -r weixin637android660.apk -f  27.28s user 2.84s system 434% cpu 6.926 total
➜  Desktop  time java -jar ShakaApktool_2.0.0-master-737fef9-20151125-release.jar d -r weixin637android660.apk -f 
I: Using ShakaApktool 2.0.0-master-737fef9-20151125
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
java -jar ShakaApktool_2.0.0-master-737fef9-20151125-release.jar d -r  -f  167.35s user 65.50s system 556% cpu 41.854 total
➜  Desktop  time java -jar ShakaApktool_2.0.0-master-1dd5a9d-20151206-release.jar d -r weixin637android660.apk -f 
I: Using ShakaApktool 2.0.0-master-1dd5a9d-20151206
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
java -jar ShakaApktool_2.0.0-master-1dd5a9d-20151206-release.jar d -r  -f  39.45s user 68.32s system 560% cpu 19.211 total

从原来的`167.35s`优化到`39.45s`,虽然比原版的`27.28s`还是慢了一些,但应该还能接受了.优化空间也不大了.也不打算继续优化下去了.

**Comment by Ezalor** [comment]
谢谢大神哦！！之前实在是太慢了点。。如果稍慢一点是可以接受的，毕竟功能比原版的强大的多啦！

大神辛苦，跪谢！
